CREATE TABLE IF NOT EXISTS orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    table_id BIGINT NOT NULL,
    customer_id BIGINT DEFAULT NULL,
    order_number VARCHAR(50) NOT NULL,

    status ENUM('RECEIVED','PREPARING','READY','COMPLETED','CANCELLED')
    NOT NULL DEFAULT 'RECEIVED',

    total_amount DECIMAL(10,2) NOT NULL,
    tax DECIMAL(10,2) NOT NULL DEFAULT '0.00',

    payment_status ENUM('PENDING','PAID','REFUNDED') DEFAULT 'PENDING',

    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY order_number (order_number)
    );



